### PR TITLE
Add policy for OpenShift CIS via the Compliance Operator

### PR DESCRIPTION
**Pull request by JAORMX**
This adds a policy that ensures a scan exists for the OpenShift CIS
benchmark. This is executed by the Compliance Operator, and thus it
requires that the installation policy is used as well.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Review by dockerymick — APPROVED** [review]
I made small updates to both files. These additions look great, thank you @JAORMX

**Comment by JAORMX** [comment]
@dockerymick thanks for the corrections!

**Pull request merged**
