### PR TITLE
Update `integrity-shield` images

### PR DESCRIPTION
**Pull request by dhaiducek**
- Update Integrity Shield images for new `stolostron` Quay org:
  - https://github.com/stolostron/backlog/issues/19358
- Other updates missed from the org rename

### CODE REVIEW

**Comment by dhaiducek** [comment]
/unhold

Builds are pushing to Quay `stolostron` now, and a `v0.3.2` was pushed, so this should be ready for review: https://quay.io/repository/stolostron/integrity-shield-operator?tab=tags

**Review by gparvin — APPROVED** [review]
Thanks Dale!

**Pull request merged**
