### PR TITLE
Update policyGenerator.yaml

### PR DESCRIPTION
**Pull request by berenss**
few minor edits into the descriptions.

### CODE REVIEW

**Review by mprahl — DISMISSED** [review]

**Comment by mprahl** [comment]
@berenss could you please add a signoff to your commit?

**Review by berenss — COMMENTED** [review]
Signed-off-by: sberens <berenss@users.noreply.github.com>

**Comment by dhaiducek** [comment]
@berenss You have to add it to the commit directly:

```shell
git commit --amend --signoff
git push --force
```

**Comment by berenss** [comment]
😂😂 you guys - I'm struggling here obviously 😂😂

**Comment by dhaiducek** [comment]
You're not the first--DCO is a little confusing (and not widely used outside of ACM). We're here to help! 🙂

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
