### PR TITLE
Revert "Add additional checks to detect if operator is running (#202)"

### PR DESCRIPTION
**Pull request by willkutler**
This reverts commit 15d084b58d982f3dc9d41267dac054df7333accb.

Signed-off-by: Will Kutler <wkutler@redhat.com>

reverting this change for now since issues like https://github.com/open-cluster-management/backlog/issues/18588 are coming up

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by dhaiducek** [comment]
I realized the Framework tests were also updated, so I'm worried the tests still won't work. I'll try to work on fixing this today and see if I can't get them to pass locally.

**Comment by mprahl** [comment]
@dhaiducek so should we revert the revert?

**Comment by dhaiducek** [comment]
Possibly--let me poke at it a bit first.

**Comment by dhaiducek** [comment]
@willkutler Please double check the snapshots on the canaries. The framework tests were updated at `2.4.2-SNAPSHOT-2021-12-17-21-46-27`. The snapshot I see referenced is `2021-12-17-20-56-13`, so we may have reverted this change too soon before the test updates made it to the pipeline.

**Pull request merged**
