### PR TITLE
Add resources to the automation operator to create the hub and collector

### PR DESCRIPTION
**Pull request by gparvin**
Add 2 key resources into the AAP policy that many people may want to
create anyway.  They can be removed if not wanted.

Signed-off-by: Gus Parvin <gparvin@redhat.com>

### CODE REVIEW

**Comment by gparvin** [comment]
/unhold
Tested yesterday and it worked great.

**Review by dhaiducek — CHANGES_REQUESTED** [review]
Nifty! These are very new to me, but it looks cool! Maybe add some notes to the comment at the top of the file and/or to the [README](https://github.com/stolostron/policy-collection/tree/main/community#configuration-management) to clarify that these are also deployed?

**Comment by gparvin** [comment]
Thanks @dhaiducek , just made some updates.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
