### PR TITLE
fix bad format in audit config

### PR DESCRIPTION
**Pull request by ch-stark**
There was a bad intendation in configuring openshift-audit.
I verified the fix provided in my env

### CODE REVIEW

**Review by yiraeChristineKim — DISMISSED** [review]

**Review by dhaiducek — CHANGES_REQUESTED** [review]
Please update the commit message for the description to be at the top with more detail on what was fixed.

**Comment by ch-stark** [comment]
no approved

**Comment by dhaiducek** [comment]
@ch-stark The "not approved" is expected because you're not an approver in the OWNERS file: https://github.com/open-cluster-management-io/policy-collection/blob/main/OWNERS

But also, I think we should not be setting anything to `remediationAction: enforce` in the policy-collection. That should be left to the user. You could put `remediationAction: inform` with a comment there instead?

**Comment by dhaiducek** [comment]
> But also, I think we should not be setting anything to `remediationAction: enforce` in the policy-collection. That should be left to the user. You could put `remediationAction: inform` with a comment there instead?

Oh, nevermind--I see it was already set to `enforce` and it was fine-tuned. 🙂

**Pull request closed without merging**
