### PR TITLE
Make it easier to install openshift gitops argocd and include health

### PR DESCRIPTION
**Pull request by gparvin**
Creating a policy set to make setup of openshift gitops easier. It sets up the generator and configures health checks for policies.

### CODE REVIEW

**Review by JustinKuli — DISMISSED** [review]
/hold

LGTM! At least, I couldn't see any issues, I figure you developed this from testing.

Just holding because it's been open 2 weeks and I don't want to surprise-merge it, feel free to unhold if it is good to go.

**Comment by ch-stark** [comment]
Do we need https://github.com/open-cluster-management-io/policy-collection/blob/1d541f6012fc668a23b7790183012a814a50c493/policygenerator/policy-sets/community/openshift-gitops/subscription-admin.yaml?

it is not used by ArgoCD.  Thanks a lot, create idea to add healthchecks

**Comment by gparvin** [comment]
> 
> it is not used by ArgoCD. Thanks a lot, create idea to add healthchecks

Thanks, I think it was a copy paste carry over from setting up the project.  I have removed the file which wasn't used.

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
