### PR TITLE
 Sample templatized policies

### PR DESCRIPTION
**Pull request by ckandag**
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>

https://github.com/stolostron/backlog/issues/18660

### CODE REVIEW

**Review by ch-stark — DISMISSED** [review]

**Review by gparvin — COMMENTED** [review]
I like these changes and hope this helps customers use template ideas to do more with policies.  My only comment is I'm not sure about some of the different delimiters that are used.

I see `{{` and `{{-`.  Similarly there's `{{hub` and `{{hub-`.  Does the `-` added to some of the delimiters serve some purpose?

**Comment by ckandag** [comment]
> I see `{{` and `{{-`. Similarly there's `{{hub` and `{{hub-`. Does the `-` added to some of the delimiters serve some purpose?

@gparvin  , the - minus sign is for trimming leading/trailing whitespaces ,  "if an action's left delimiter (by default "{{") is followed immediately by a minus sign and white space, all trailing white space is trimmed from the immediately preceding text. Similarly, if the right delimiter ("}}") is preceded by white space and a minus sign, all leading white space is trimmed from the immediately following text."
https://pkg.go.dev/text/template#hdr-Text_and_spaces

**Review by gparvin — APPROVED** [review]
The comments helped a lot here.  Thanks for all the details you included.  This looks good to me.

**Pull request merged**
