### PR TITLE
Gatekeeper policies from Red Hat CoP

### PR DESCRIPTION
**Pull request by sabre1041**
Initial incorporation of Gatekeeper policies from the [Red Hat Community of Practice (CoP) policies repository](https://github.com/redhat-cop/rego-policies).

* Containers using the `latest` image tag
* Containers without Readiness Probes
* Containers without Liveness Probes

The CoP makes use of [Konstraint](https://github.com/plexsystems/konstraint) libraries. Improvements could be made to remove the functions that are not being used.

### CODE REVIEW

**Comment by ycao56** [comment]
@sabre1041 can you also update https://github.com/open-cluster-management/policy-collection/tree/master/community to include these three policies with a short descriptions and prereqs? We will have @dockerymick from ID to review text.

**Comment by ycao56** [comment]
seems good. @dockerymick can you review the text?

**Review by ycao56 — APPROVED** [review]

**Review by willkutler — APPROVED** [review]

**Comment by dockerymick** [comment]
Thanks for your patience, and thanks for the reminder @ycao56. I am taking a look at the PR now

**Review by dockerymick — APPROVED** [review]
Made a few updates for the table descriptions

**Pull request merged**
