### PR TITLE
Updating the link to psp policy yaml

### PR DESCRIPTION
**Pull request by dockerymick**
Signed-off-by: Mikela Jackson <mdockery@redhat.com>

### CODE REVIEW

**Review by gparvin — COMMENTED** [review]
I think we should delete this entry in the community readme, since it looks like we are pointing to the stable policy.  The note here should get copied to the stable readme.  That way we won't have this policy listed in 2 readmes with different info.

**Comment by dockerymick** [comment]
@gparvin Thanks for your feedback ! Making sure that I understood your suggestion, you are suggesting that the Pod Security Policy entry should be removed from the community/README only? I saw that it is linked correctly in the [stable README](https://github.com/stolostron/policy-collection/tree/main/stable#system-and-communications-protection).

**Comment by gparvin** [comment]
@dockerymick Yes, since it is already linked correctly in the stable README, it should not be listed at all in the community readme, it just needs to be removed.  I see that we deprecated this policy -- so I suspect there may have been some movement of this policy that caused some confusion.  I'll open a doc issue because I see a bad link there too.

**Comment by dockerymick** [comment]
@gparvin Sounds good! Thanks for opening a doc issue

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
