### PR TITLE
Zts cmc stable

### PR DESCRIPTION
**Pull request by mahesh-zetta**

### CODE REVIEW

**Comment by gparvin** [comment]
@mahesh-zetta Our stable folder has 2 readme files to update.  The one you updated and a second one in the `stable` folder (the parent directory).  Can you add some extra details so consumers of this policy will have a link to your product and will know how it's special compared to the other pod policy?  Thanks!

**Comment by mahesh-zetta** [comment]
> @mahesh-zetta Our stable folder has 2 readme files to update. The one you updated and a second one in the `stable` folder (the parent directory). Can you add some extra details so consumers of this policy will have a link to your product and will know how it's special compared to the other pod policy? Thanks!

@gparvin ,   I just added a README entry to the repository.  Should I open a new PR?  Thanks.

**Comment by gparvin** [comment]
@mahesh-zetta Thanks for adding the readme.  You still should add some more details to the readme with information like a link to how to use Zettaset like in the community readme you created.  There you added: "See the [Zettaset README](https://github.com/zettaset/zettaset-public/) to learn more about Zettaset CMC Deployment."
Also, the commit sign off needs to be done.  There's some more details here: https://github.com/stolostron/policy-collection/blob/main/CONTRIBUTING.md#dco-sign-off.  Take a look at that info to help get your commits signed.

**Comment by mahesh-zetta** [comment]
> @mahesh-zetta Thanks for adding the readme. You still should add some more details to the readme with information like a link to how to use Zettaset like in the community readme you created. There you added: "See the [Zettaset README](https://github.com/zettaset/zettaset-public/) to learn more about Zettaset CMC Deployment." Also, the commit sign off needs to be done. There's some more details here: https://github.com/stolostron/policy-collection/blob/main/CONTRIBUTING.md#dco-sign-off. Take a look at that info to help get your commits signed.

@gparvin ,  The signoff's in this PR, require some intermediate files to be signed off.  These files have somehow been deleted.  Is it fine if I open a new PR with the changes, with just the 2 file changes ?  Thanks, Mahesh

**Comment by gparvin** [comment]
THat would be great.  Thanks!

**Comment by mahesh-zetta** [comment]
https://github.com/stolostron/policy-collection/pull/322

Replaced 320 with 322.

**Pull request closed without merging**
