### PR TITLE
Add additional checks to detect if operator is running

### PR DESCRIPTION
**Pull request by ycao56**
Add additional checks to detect if operator is running

resolves https://github.com/open-cluster-management/backlog/issues/18566

Signed-off-by: Yu Cao <ycao@redhat.com>

### CODE REVIEW

**Comment by ycao56** [comment]
@jnpacker @ch-stark FYI

**Review by dhaiducek — APPROVED** [review]
This looks good!

Is the CSV the most reliable check you found? I was thinking from a generator perspective, it would be simpler to generate a `status` check for a resource that was already provided (otherwise the user is pretty much writing the entire policy). Maybe something like:
```yaml
- complianceType: mustnothave
  objectDefinition:
    <reuse metadata from a given resource, like the subscription>
    status:
      catalogHealth:
      - healthy: false
```
I'll look into it for the generator, but from what you've seen would something like that work to check the health of the Subscription or does that not really report on the resources it backs?

**Comment by ycao56** [comment]
@dhaiducek Yeah, I don't think checking subscription status field is enough. I found CSV is more reliable based on my testing. If for some reason the pods are not installed an running, CSV would return phase `Failed` or `Installing`. Subscription couldn't show that granularity.

**Pull request merged**
