### PR TITLE
this appears to be an extra entry

### PR DESCRIPTION
**Pull request by gparvin**
I don't see anything missing.  I think this entry just isn't needed.

### CODE REVIEW

**Comment by ycao56** [comment]
@gparvin I think this should be right link https://github.com/open-cluster-management/policy-collection/blob/main/community/CM-Configuration-Management/policy-github-oauth-sample.yaml

**Comment by ycao56** [comment]
can you fix it?

**Comment by ycao56** [comment]
nvm you are right. this is not needed

**Comment by petr-muller** [comment]
@ycao56 @gparvin This PR hit a GH limit on the number of statuses on a SHA and Prow now cannot merge it. The reason for this is that you made it Tide-mergeable with slash-commands, but your repo is at the same time configured to only allow merges when a PR has an **approving GH review**.

In order for this PR to merge, it needs to be amended (so that it gets a new SHA) and then approved via GH review. Long-term, I suggest to disable the custom merge criteria b/c you have Tide configured.

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
