### PR TITLE
Undeploy script

### PR DESCRIPTION
**Pull request by dhaiducek**
This undeploy script (AKA `remove.sh`) will look for matching `<prefix>-chan` Channel and `<prefix>-sub` Subscription resources and remove them in tandem.

Neither a namespace nor a prefix is required--the script will poll the cluster for both if not provided.

If the Subscription has been changed and no longer points to the Channel, the script refuses to delete the resource but gives the user a warning and the commands to do it themselves.

### CODE REVIEW

**Comment by ycao56** [comment]
adding @dockerymick to take a look at doc

**Comment by ycao56** [comment]
Is `oc` a hard requirement for user to run this script? Can we do the same with just kubectl?

**Review by gparvin — APPROVED** [review]
Thanks for adding this enhancement!

**Comment by dhaiducek** [comment]
Yes, `oc` is a hard requirement because it allows the script to find and iterate over the available namespaces. I'm not aware of a way to find available namespaces otherwise.

I changed `deploy.sh` to use `oc` also, but I can change it back to `kubectl` if it needs to be more generic. I was thinking the scripts would both be pointing at an Openshift RHACM hub, but maybe that's a poor assumption? If so, I can adjust the script to require a namespace be provided if a user doesn't have clusterwide access and move everything to `kubectl`.

**Comment by ycao56** [comment]
I think it's not a problem for now. But in the future, after we open source the framework code, it should not require openshift to deploy and test. So it's better to make oc optional.

**Comment by dhaiducek** [comment]
Ah, okay. Let me make that change now so that we don't have to worry about it later.

**Review by dockerymick — COMMENTED** [review]
Made updates to the README @dhaiducek let me know what you think

**Review by dockerymick — APPROVED** [review]
Made an update for clarity

**Comment by dhaiducek** [comment]
@dockerymick I made some additional adjustments to your edits. Most notably, I replaced "View the following example..." with "View the following guidance..." since to me it's not an example. And I also added a note that parameters are optional. What do you think?

**Review by ycao56 — APPROVED** [review]

**Comment by dockerymick** [comment]
@dhaiducek great idea, i agree with your change

**Pull request merged**
