### PR TITLE
Add DCO

### PR DESCRIPTION
**Pull request by dhaiducek**

### CODE REVIEW

**Review by dockerymick — DISMISSED** [review]
I made some small changes. I spelled out `repo`. This looks good to me, thanks Dale!

**Comment by ycao56** [comment]
Is there a doc for how to sign the commit to pass DCO check?

**Comment by dhaiducek** [comment]
I don't think there's a lot of clarity on that. I'm still figuring it out. The best thing I've found so far is this:
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
