### PR TITLE
Transition policy-podsecuritypolicy to community

### PR DESCRIPTION
**Pull request by mprahl**
A PodSecurityPolicy Kubernetes resource object does not do anything in
OpenShift as described here:
https://access.redhat.com/solutions/5622051

Because of this, it was decided to remove the stable designation of the
policy-podsecuritypolicy policy. This decision can be seen here:
https://github.com/open-cluster-management/backlog/issues/16574#issuecomment-936229736

Resolves:
https://github.com/open-cluster-management/backlog/issues/16574

### CODE REVIEW

**Review by ycao56 — CHANGES_REQUESTED** [review]
@mprahl Following READMEs also need to be updated
1. https://github.com/open-cluster-management/policy-collection/tree/main/stable/README.md
2. https://github.com/open-cluster-management/policy-collection/tree/main/stable/SC-System-and-Communications-Protection/README.md
3. https://github.com/open-cluster-management/policy-collection/blob/main/community/README.md

**Comment by mprahl** [comment]
> @mprahl Following READMEs also need to be updated
> 
> 1. https://github.com/open-cluster-management/policy-collection/tree/main/stable/README.md
> 2. https://github.com/open-cluster-management/policy-collection/tree/main/stable/SC-System-and-Communications-Protection/README.md
> 3. https://github.com/open-cluster-management/policy-collection/blob/main/community/README.md

Sorry for missing that. Please rereview the PR.

**Review by ycao56 — APPROVED** [review]

**Comment by berenss** [comment]
hello team - I do not agree to move a well defined Kubernetes policy from `Stable` into `Community`.
We are open-cluster-management. we are RHACM for Kubernetes. We need to deliver `stable` **Kubernetes** policies.
cc: @ch-stark

**Comment by ycao56** [comment]
@berenss PSP has been deprecated see https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
The recommendation is to use gatekeeper and kyverno. There will also be a `PSP Replacement Policy` coming in the future.
So I am leaning towards to come up with a gatekeeper policy alternative for stable folder.

**Comment by berenss** [comment]
PSP will be around for months...years, until the levels of kubernetes that we support follow the end of that deprecation. Please do not move PSP out of stable until the full deprecation.

**Pull request merged**
